name: Build In Runner

on:
  push:
    branches:
      - test_pipelines
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        otp-version: '25.3'
        elixir-version: '1.15.5'

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19.6'

    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        MIX_ENV=prod mix deps.get
        npm install --prefix assets
        mix assets.setup
        mix assets.build
        mix assets.deploy
        mix phx.digest

    - name: Build release
      run: |
        MIX_ENV=prod mix release --overwrite --path ../mazaryn_release_new
        ls -alh ../mazaryn_release_new
        tar -czvf mazaryn_release.tar.gz ../mazaryn_release_new

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mazaryn_release
        path: mazaryn_release.tar.gz
