name: Deploy to bare-metal

on:
  push:
    branches:
      - test_pipelines
jobs:
  deploy:
    name: Deploy || Restore 
    runs-on: ubuntu-latest
    steps:
    - name: get artifacts from github releases
      id: download
      uses: dawidd6/action-download-artifact@v2.28.0
      with:
        name: mazaryn_release
        path: mazaryn_release.tar.gz
    
    - uses: actions/checkout@v3
    - name: push artifact to remote server
      id: deploy
      if: steps.download.outcome == 'success'
      uses: up9cloud/action-rsync@master
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USER: ${{ secrets.SSH_USER }}
        PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SOURCE: mazaryn_release.tar.gz
        TARGET: /home/zaryn/mazaryn_release.tar.gz
        
    - name: executing remote ssh commands to trigger new build install
      id: install
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
           tar -xvf mazaryn_release.tar.gz 
           echo "listing"
           ls -alh

    - name: executing remote ssh commands to deploy new build
      id: deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          sudo systemctl daemon-reload
          sudo systemctl stop mazaryn.service
          rm -rf mazaryn_release_backup_1
          mv -f mazaryn_release_backup mazaryn_release_backup_1 && mv -f mazaryn_release mazaryn_release_backup && mv -f mazaryn_release_new mazaryn_release
          sudo systemctl start mazaryn.service
    
    - name: checking successful deployment otherwise restore older version
      id: health
      if: steps.deployment.outcome == 'failure'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          journalctl -u mazaryn.service
          sudo systemctl stop mazaryn.service
          rm -rf mazaryn_release_failed
          mv -f mazaryn_release mazaryn_release_failed && mv -f mazaryn_release_backup mazaryn_release
          sudo systemctl daemon.reload
          sudo systemctl start mazaryn.service
          echo "BUILD FAILED, PREVIOUS VERSION RESTORED"
          exit 1
          
          
