name: Deploy to bare-metal

on:
  push:
    branches:
      - fix_flow
jobs:
  deploy:
    name: Build && Deploy || Restore 
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to trigger new build
      id: build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
           cd mazaryn
           sudo mv rel/overlays/mazaryn.service /etc/systemd/system/mazaryn.service
           git reset --hard
           git checkout main
           git pull
           source ~/.bashrc
           export PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
           mix local.hex --force
           mix local.rebar --force
           mix deps.get
           mix assets.setup
           mix assets.build
           npm install --prefix assets
           mix assets.deploy
           mix phx.digest
           mix release --overwrite --path ../mazaryn_release_new

    - name: executing remote ssh commands to deploy new build
      id: deployment
      if: steps.build.outcome == 'success'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          sudo systemctl daemon-reload
          sudo systemctl stop mazaryn.service
          rm -rf mazaryn_release_backup_1
          mv -f mazaryn_release_backup mazaryn_release_backup_1 && mv -f mazaryn_release mazaryn_release_backup && mv -f mazaryn_release_new mazaryn_release
          sudo systemctl start mazaryn.service
    
    - name: checking successful deployment otherwise restore older version
      id: health
      if: steps.deployment.outcome == 'failure'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          journalctl -u mazaryn.service
          sudo systemctl stop mazaryn.service
          rm -rf mazaryn_release_failed
          mv -f mazaryn_release mazaryn_release_failed && mv -f mazaryn_release_backup mazaryn_release
          sudo systemctl daemon.reload
          sudo systemctl start mazaryn.service
          echo "BUILD FAILED, PREVIOUS VERSION RESTORED"
          exit 1
          